export const elements = {
  taskNodes: [
    {
      data: {
        id: 'accountManagement:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'accountManagement',
        title: 'Describe user access needs',
        parent: 'Plan & Design',
        receivedAttributesSet: {},
        providedAttributes: [
          'initiative_accountTypes',
          'initiative_accountExternalAuth',
          'initiative_accountAuthentication',
          'initiative_accountAuthorization',
        ],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'architectureAssuranceHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'architectureAssuranceHolding',
        title: 'Architecture Assurance Holding Task',
        parent: 'Plan & Design',
        receivedAttributesSet: {},
        providedAttributes: [
          'initiative_architectureAssuranceInitialArchitectureReviewRequestApproval',
        ],
        isHoldingTask: true,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'solutionDesign:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'solutionDesign',
        title: 'Confirm solution design',
        parent: 'Plan & Design',
        receivedAttributesSet: {},
        providedAttributes: [
          'initiative_editTechList',
          'initiative_newTechnologies',
          'initiative_caiAppDetails',
          'initiative_location',
          'initiative_externalVendorsDev',
          'initiative_techType',
          'initiative_derivedExistingTechnologies',
          'initiative_caiAppExistsInServiceNow',
        ],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'voyagerSetup',
        title: 'Complete Voyager setup',
        parent: 'Initiation',
        receivedAttributesSet: {},
        providedAttributes: [
          'initiative_type',
          'initiative_name',
          'initiative_key',
          'initiative_stealthAuditConfirmation',
          'initiative_newProjectConfirmation',
          'initiative_agileBoardType',
          'initiative_voyagerExtensionConfirmation',
          'initiative_adoWebhookConfirmation',
          'initiative_agileBoardServiceAccountConfirmation',
          'initiative_adoBoardUrl',
          'initiative_jiraBoardUrl',
        ],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Complete',
        color: '#006607',
        highlight: '#8feb95',
      },
    },
    {
      data: {
        id: 'applicationRiskAssessment:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'applicationRiskAssessment',
        title: 'Complete Application Risk Assessment (ARA)',
        parent: 'Plan & Design',
        receivedAttributesSet: {},
        providedAttributes: [
          'initiative_applicationRiskAssessmentConfirm',
          'initiative_applicationRiskAssessmentURL',
        ],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'architectureAssurance:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'architectureAssurance',
        title: 'Initiate Architecture Assurance',
        parent: 'Plan & Design',
        receivedAttributesSet: {},
        providedAttributes: [
          'initiative_newOrExisting',
          'initiative_infraChanges',
          'initiative_interfaceNumber',
          'initiative_usedByOtherBU',
          'initiative_approximatelyHowManyUsers',
          'initiative_approximatelyHowMuchData',
          'initiative_approximatelyHowMuchInfrastructure',
          'initiative_architectureSignificanceScore',
        ],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        serviceNowAttribute: 'initiative_architectureAssuranceInitialArchitectureReviewRequest',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'dataClassification:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'dataClassification',
        title: 'Classify data usage',
        parent: 'Plan & Design',
        receivedAttributesSet: {},
        providedAttributes: [
          'initiative_classify',
          'initiative_personalInformation',
          'initiative_dataSets',
          'initiative_appOnOffPayments',
          'initiative_regulationGuidelines',
          'initiative_confidentialTransaction',
          'initiative_requiresDataFromOtherApp',
        ],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'developmentEnvironmentProvisioning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'developmentEnvironmentProvisioning',
        title: 'Build development environment',
        parent: 'Plan & Design',
        receivedAttributesSet: {},
        providedAttributes: [
          'initiative_usingPolaris',
          'initiative_githubAdminUsername',
          'initiative_templateType',
          'initiative_polarisDatastore',
          'initiative_amsServices',
          'initiative_developmentEnvironmentCreated',
        ],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'externalSources:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'externalSources',
        title: 'Describe external sourcing requirements',
        parent: 'Plan & Design',
        receivedAttributesSet: {},
        providedAttributes: ['initiative_externalSources'],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'externalVendor:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'externalVendor',
        title: 'Describe external vendor requirements',
        parent: 'Plan & Design',
        receivedAttributesSet: {},
        providedAttributes: [
          'initiative_externalAssistancePerformingDev',
          'initiative_externalVendorMaintenance',
        ],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'externalWebsites:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'externalWebsites',
        title: 'Confirm external website use',
        parent: 'Plan & Design',
        receivedAttributesSet: {},
        providedAttributes: ['initiative_externalWebsites'],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'performanceLoadTestingProcessEngagement:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'performanceLoadTestingProcessEngagement',
        title: 'Engage Performance and Load testing team',
        parent: 'Plan & Design',
        receivedAttributesSet: {},
        providedAttributes: ['initiative_performanceLoadTestingEngagementConfirm'],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'securityDesignReview:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'securityDesignReview',
        title: 'Complete Security Design Review (SDR)',
        parent: 'Plan & Design',
        receivedAttributesSet: {},
        providedAttributes: ['initiative_securityDesignReviewConfirmation'],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'securityInformationEventManagement:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'securityInformationEventManagement',
        title: 'Confirm SIEM logging',
        parent: 'Build, Test & Deploy',
        receivedAttributesSet: {},
        providedAttributes: ['initiative_siemConfirm', 'initiative_siemURL'],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'serviceTakeOn:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'serviceTakeOn',
        title: 'Initiate Service Take-on (STO)',
        parent: 'Build, Test & Deploy',
        receivedAttributesSet: {},
        providedAttributes: ['initiative_primarySupportGroup', 'initiative_changeApprovalGroup'],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        serviceNowAttribute: 'initiative_applicationRegistrationStatus',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'governance:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'governance',
        title: 'Confirm project governance',
        parent: 'Governance',
        receivedAttributesSet: {},
        providedAttributes: [
          'initiative_stakeholders',
          'initiative_planviewSnapshot',
          'initiative_registeringApplicationCompleted',
          'initiative_abandon',
          'initiative_abandonReason',
        ],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'solutionIntent:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'solutionIntent',
        title: 'Confirm solution intent',
        parent: 'Initiation',
        receivedAttributesSet: {},
        providedAttributes: [
          'initiative_description',
          'initiative_proposedNewTechnologies',
          'initiative_sponsorBusinessUnit',
          'initiative_technologyGroup',
          'initiative_tpmEmail',
          'initiative_derivedProposedExistingTechnologies',
        ],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Active',
        color: '#ea9b00',
        highlight: '#fadca2',
      },
    },
    {
      data: {
        id: 'amsServiceRequest:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'amsServiceRequest',
        title: 'Request AMS Services',
        parent: 'Plan & Design',
        receivedAttributesSet: {},
        providedAttributes: ['initiative_amsServiceRequestConfirm'],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'disasterRecoveryPlanning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'disasterRecoveryPlanning',
        title: 'Determine Disaster Recovery Planning requirements',
        parent: 'Build, Test & Deploy',
        receivedAttributesSet: {},
        providedAttributes: [
          'initiative_recoveryTier',
          'initiative_excludedDRTesting',
          'initiative_dateDRTest',
          'initiative_drPlanURL',
          'initiative_dateLastDRTest',
          'initiative_cisoConsentURL',
        ],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'dynamicApplicationSecurityTesting:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'dynamicApplicationSecurityTesting',
        title: 'Implement Dynamic Application Security Testing (DAST)',
        parent: 'Build, Test & Deploy',
        receivedAttributesSet: {},
        providedAttributes: [
          'initiative_dynamicApplicationSecurityTestingConfirm',
          'initiative_penetrationTesting',
          'initiative_cisoDASTConsentURL',
        ],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'encryptionAtRest:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'encryptionAtRest',
        title: 'Perform Encryption@Rest',
        parent: 'Build, Test & Deploy',
        receivedAttributesSet: {},
        providedAttributes: [
          'initiative_encryptionAtRestConfirm',
          'initiative_encryptionAtRestEnableLink',
          'initiative_encryptionAtRestTool',
          'initiative_encryptionAtRestAlgorithm',
        ],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'encryptionInTransit:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'encryptionInTransit',
        title: 'Perform Encryption in Transit',
        parent: 'Build, Test & Deploy',
        receivedAttributesSet: {},
        providedAttributes: [
          'initiative_encryptConfirm',
          'initiative_encryptSPI',
          'initiative_encryptMethodsApproved',
        ],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Active',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'fullArchitectureReview:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'fullArchitectureReview',
        title: 'Full Architecture Review',
        parent: 'Plan & Design',
        receivedAttributesSet: {},
        providedAttributes: [],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        serviceNowAttribute: 'initiative_architectureAssuranceFullArchitectureReviewRequest',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'initialSolutionCompliance:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'initialSolutionCompliance',
        title: 'Confirm initial solution compliance',
        parent: 'Initiation',
        receivedAttributesSet: {},
        providedAttributes: [
          'initiative_restrictedCountries',
          'initiative_receivedConsent',
          'initiative_copyConsentAttachment',
          'initiative_abandon',
          'initiative_abandonReason',
        ],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        serviceNowAttribute: 'initiative_architectureAssuranceProjectReviewRequest',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'multifactorAuthentication:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'multifactorAuthentication',
        title: 'Complete Multifactor Authentication (MFA)',
        parent: 'Build, Test & Deploy',
        receivedAttributesSet: {},
        providedAttributes: [
          'initiative_multifactorAuthenticationConfirmation',
          'initiative_multifactorAuthenticationTool',
          'initiative_multifactorAuthenticationToolName',
          'initiative_multifactorAuthenticationURL',
        ],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'performanceLoadTestingProcessCompletion:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'performanceLoadTestingProcessCompletion',
        title: 'Complete Performance and Load testing',
        parent: 'Plan & Design',
        receivedAttributesSet: {},
        providedAttributes: ['initiative_statusPerformanceLoadTesting'],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'privacyRiskAssessment:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'privacyRiskAssessment',
        title: 'Complete Privacy Risk Assessment (PRA)',
        parent: 'Plan & Design',
        receivedAttributesSet: {},
        providedAttributes: ['initiative_praConfirm', 'initiative_praURL'],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'productionEnvironmentProvisioning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'productionEnvironmentProvisioning',
        title: 'Confirm pre-production and production environment provisioning',
        parent: 'Build, Test & Deploy',
        receivedAttributesSet: {},
        providedAttributes: ['initiative_productionEnvironmentProvisioned'],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'serviceDeskKnowledgeBase:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'serviceDeskKnowledgeBase',
        title: 'Create Service Desk Knowledge Base',
        parent: 'Build, Test & Deploy',
        receivedAttributesSet: {},
        providedAttributes: ['initiative_serviceDeskKBConfirm'],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'softwareCompositionAnalysis:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'softwareCompositionAnalysis',
        title: 'Implement Software Composition Analysis (SCA)',
        parent: 'Build, Test & Deploy',
        receivedAttributesSet: {},
        providedAttributes: ['initiative_softwareCompositionAnalysisConfirm'],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'staticApplicationSecurityTesting:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'staticApplicationSecurityTesting',
        title: 'Implement Static Application Security Testing (SAST)',
        parent: 'Build, Test & Deploy',
        receivedAttributesSet: {},
        providedAttributes: ['initiative_staticApplicationSecurityTestingConfirm'],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'thirdPartyRiskAssessment:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'thirdPartyRiskAssessment',
        title: 'Complete 3rd Party Risk Assessment (3PRA)',
        parent: 'Plan & Design',
        receivedAttributesSet: {},
        providedAttributes: [
          'initiative_thirdPartyRiskAssessmentConfirm',
          'initiative_thirdPartyRiskAssessmentURL',
        ],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'vendorRiskAssessment:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'vendorRiskAssessment',
        title: 'Complete Vendor Risk Assessment (VRA)',
        parent: 'Plan & Design',
        receivedAttributesSet: {},
        providedAttributes: [
          'initiative_vendorRiskAssessmentConfirm',
          'initiative_vendorRiskAssessmentURL',
        ],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Active',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'vulnerabilityRemediation:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'vulnerabilityRemediation',
        title: 'Complete Vulnerability Management process',
        parent: 'Build, Test & Deploy',
        receivedAttributesSet: {},
        providedAttributes: [
          'initiative_identifiedVulnerabilities',
          'initiative_remediatedVulnerabilities',
          'initiative_vulnerabilitiesRiskAcceptanceURL',
        ],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'websiteMonitoring:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'websiteMonitoring',
        title: 'Implement Website Monitoring',
        parent: 'Build, Test & Deploy',
        receivedAttributesSet: {},
        providedAttributes: [
          'initiative_completedWebsiteMonitoringForm',
          'initiative_websiteMonitoringConfirm',
        ],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'polarisConfirmation:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'polarisConfirmation',
        title: 'Complete Polaris Blueprint form',
        parent: 'Plan & Design',
        receivedAttributesSet: {},
        providedAttributes: ['initiative_polarisBlueprintConfirmation'],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Active',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'fullArchitectureReviewHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'fullArchitectureReviewHolding',
        title: 'Full Architecture Review Holding Task',
        parent: 'Plan & Design',
        receivedAttributesSet: {},
        providedAttributes: [
          'initiative_architectureAssuranceFullArchitectureReviewRequestApproval',
        ],
        isHoldingTask: true,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'serviceTakeOnHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'serviceTakeOnHolding',
        title: 'Service Take-on (STO) Holding Task',
        parent: 'Build, Test & Deploy',
        receivedAttributesSet: {},
        providedAttributes: ['initiative_applicationRegistrationStatusApproval'],
        isHoldingTask: true,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'projectReviewHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'projectReviewHolding',
        title: 'Project Review Holding Task',
        parent: 'Initiation',
        receivedAttributesSet: {},
        providedAttributes: ['initiative_architectureAssuranceProjectReviewRequestApproval'],
        isHoldingTask: true,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'ssdlc:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        name: 'ssdlc',
        title: 'Complete S-SDLC Risk Rating Score',
        parent: 'Plan & Design',
        receivedAttributesSet: {},
        providedAttributes: ['initiative_SSDLCRiskRating'],
        isHoldingTask: false,
        isComplex: false,
        primaryEntityType: 'initiative',
        entityKey: {
          initiative: 'asd',
        },
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'technicalRiskAssessment',
        name: 'technicalRiskAssessment',
        title: 'Complete Technical Risk Assessment (TRA)',
        parent: 'Plan & Design',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_technologyInstalledProduction',
          'etiItem-initiative_technologyInstalledProductionJustification',
          'etiItem-initiative_technologyLiveData',
          'etiItem-initiative_technologyLiveDataJustification',
          'etiItem-initiative_businessCase',
          'etiItem-initiative_technologyStartDate',
          'etiItem-initiative_technologyRiskAssessmentPriority',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_technicalRiskAssessmentRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'technicalRiskAssessmentHolding',
        name: 'technicalRiskAssessmentHolding',
        title: 'Technical Risk Assessment Holding',
        parent: 'Plan & Design',
        receivedAttributesSet: {},
        providedAttributes: ['etiItem-initiative_technicalRiskAssessmentRequestApproval'],
        isHoldingTask: true,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcessHolding',
        name: 'cloudServiceOnboardingProcessHolding',
        title: 'Cloud Service Onboarding Process Holding',
        parent: 'Plan & Design',
        receivedAttributesSet: {},
        providedAttributes: ['etiItem-initiative_cloudServiceOnboardingRequestApproval'],
        isHoldingTask: true,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'cloudServiceOnboardingProcess',
        title: 'Evaluate Cloud Service Onboarding (CSOP) services',
        parent: 'Plan & Design',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess',
        name: 'testTask',
        title: 'Unimplemented Task',
        parent: 'Unimplemented',
        receivedAttributesSet: {},
        providedAttributes: [
          'etiItem-initiative_cloudPlatformService',
          'etiItem-initiative_cloudPrivateNetwork',
          'etiItem-initiative_cloudFedRAMPCompliant',
          'etiItem-initiative_cloudAuthorizedCISO',
          'etiItem-initiative_cloudAuthorizedCISOURL',
        ],
        isHoldingTask: false,
        isComplex: true,
        primaryEntityType: 'etiItem-initiative',
        serviceNowAttribute: 'etiItem-initiative_cloudServiceOnboardingRequest',
        entityKey: {},
        status: 'Future',
        color: '#b8b8b8',
        highlight: '#e0e0e0',
      },
    },
  ],
  visibleEdges: [
    {
      data: {
        id: 'architectureAssuranceHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-accountManagement:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'architectureAssuranceHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'accountManagement:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'solutionDesign:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-accountManagement:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'solutionDesign:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'accountManagement:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'developmentEnvironmentProvisioning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-amsServiceRequest:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'developmentEnvironmentProvisioning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'amsServiceRequest:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'architectureAssuranceHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-applicationRiskAssessment:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'architectureAssuranceHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'applicationRiskAssessment:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'solutionDesign:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-architectureAssurance:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'solutionDesign:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'architectureAssurance:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'architectureAssurance:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-architectureAssuranceHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'architectureAssurance:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'architectureAssuranceHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'architectureAssuranceHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-cloudServiceOnboardingProcess',
        source: 'architectureAssuranceHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'cloudServiceOnboardingProcess',
      },
    },
    {
      data: {
        id: 'solutionDesign:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-cloudServiceOnboardingProcess',
        source: 'solutionDesign:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'cloudServiceOnboardingProcess',
      },
    },
    {
      data: {
        id: 'cloudServiceOnboardingProcess-cloudServiceOnboardingProcessHolding',
        source: 'cloudServiceOnboardingProcess',
        target: 'cloudServiceOnboardingProcessHolding',
      },
    },
    {
      data: {
        id: 'architectureAssuranceHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-dataClassification:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'architectureAssuranceHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'dataClassification:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'solutionDesign:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-dataClassification:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'solutionDesign:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'dataClassification:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'architectureAssuranceHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-developmentEnvironmentProvisioning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'architectureAssuranceHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'developmentEnvironmentProvisioning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'solutionDesign:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-developmentEnvironmentProvisioning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'solutionDesign:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'developmentEnvironmentProvisioning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'fullArchitectureReviewHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-disasterRecoveryPlanning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'fullArchitectureReviewHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'disasterRecoveryPlanning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'productionEnvironmentProvisioning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-dynamicApplicationSecurityTesting:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'productionEnvironmentProvisioning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'dynamicApplicationSecurityTesting:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'dataClassification:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-encryptionAtRest:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'dataClassification:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'encryptionAtRest:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'ssdlc:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-encryptionAtRest:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'ssdlc:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'encryptionAtRest:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'externalWebsites:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-encryptionInTransit:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'externalWebsites:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'encryptionInTransit:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'ssdlc:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-encryptionInTransit:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'ssdlc:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'encryptionInTransit:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'architectureAssuranceHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-externalSources:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'architectureAssuranceHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'externalSources:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'architectureAssuranceHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-externalVendor:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'architectureAssuranceHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'externalVendor:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'architectureAssuranceHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-externalWebsites:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'architectureAssuranceHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'externalWebsites:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'applicationRiskAssessment:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-fullArchitectureReview:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'applicationRiskAssessment:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'fullArchitectureReview:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'dataClassification:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-fullArchitectureReview:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'dataClassification:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'fullArchitectureReview:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'developmentEnvironmentProvisioning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-fullArchitectureReview:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'developmentEnvironmentProvisioning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'fullArchitectureReview:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'externalSources:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-fullArchitectureReview:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'externalSources:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'fullArchitectureReview:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'externalVendor:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-fullArchitectureReview:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'externalVendor:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'fullArchitectureReview:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'externalWebsites:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-fullArchitectureReview:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'externalWebsites:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'fullArchitectureReview:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'privacyRiskAssessment:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-fullArchitectureReview:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'privacyRiskAssessment:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'fullArchitectureReview:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'thirdPartyRiskAssessment:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-fullArchitectureReview:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'thirdPartyRiskAssessment:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'fullArchitectureReview:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'fullArchitectureReview:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-fullArchitectureReviewHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'fullArchitectureReview:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'fullArchitectureReviewHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'projectReviewHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-governance:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'projectReviewHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'governance:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'solutionIntent:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-initialSolutionCompliance:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'solutionIntent:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'initialSolutionCompliance:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'dataClassification:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-multifactorAuthentication:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'dataClassification:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'multifactorAuthentication:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'ssdlc:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-multifactorAuthentication:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'ssdlc:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'multifactorAuthentication:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'performanceLoadTestingProcessEngagement:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-performanceLoadTestingProcessCompletion:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'performanceLoadTestingProcessEngagement:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'performanceLoadTestingProcessCompletion:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'architectureAssurance:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-performanceLoadTestingProcessEngagement:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'architectureAssurance:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'performanceLoadTestingProcessEngagement:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'architectureAssuranceHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-performanceLoadTestingProcessEngagement:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'architectureAssuranceHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'performanceLoadTestingProcessEngagement:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'developmentEnvironmentProvisioning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-polarisConfirmation:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'developmentEnvironmentProvisioning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'polarisConfirmation:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'dataClassification:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-privacyRiskAssessment:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'dataClassification:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'privacyRiskAssessment:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'externalWebsites:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-privacyRiskAssessment:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'externalWebsites:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'privacyRiskAssessment:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'fullArchitectureReviewHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-productionEnvironmentProvisioning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'fullArchitectureReviewHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'productionEnvironmentProvisioning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'initialSolutionCompliance:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-projectReviewHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'initialSolutionCompliance:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'projectReviewHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'architectureAssurance:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-securityDesignReview:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'architectureAssurance:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'securityDesignReview:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'architectureAssuranceHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-securityDesignReview:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'architectureAssuranceHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'securityDesignReview:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'architectureAssuranceHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-securityInformationEventManagement:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'architectureAssuranceHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'securityInformationEventManagement:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'fullArchitectureReviewHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-serviceDeskKnowledgeBase:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'fullArchitectureReviewHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'serviceDeskKnowledgeBase:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'fullArchitectureReviewHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-serviceTakeOn:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'fullArchitectureReviewHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'serviceTakeOn:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'solutionDesign:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-serviceTakeOn:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'solutionDesign:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'serviceTakeOn:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'serviceTakeOn:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-serviceTakeOnHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'serviceTakeOn:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'serviceTakeOnHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'productionEnvironmentProvisioning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-softwareCompositionAnalysis:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'productionEnvironmentProvisioning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'softwareCompositionAnalysis:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'governance:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-solutionDesign:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'governance:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'solutionDesign:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'solutionIntent:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-solutionDesign:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'solutionIntent:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'solutionDesign:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-solutionIntent:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'solutionIntent:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'fullArchitectureReviewHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-ssdlc:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'fullArchitectureReviewHolding:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'ssdlc:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'productionEnvironmentProvisioning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-staticApplicationSecurityTesting:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'productionEnvironmentProvisioning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'staticApplicationSecurityTesting:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'dataClassification:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-technicalRiskAssessment',
        source: 'dataClassification:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'technicalRiskAssessment',
      },
    },
    {
      data: {
        id: 'technicalRiskAssessment-technicalRiskAssessmentHolding',
        source: 'technicalRiskAssessment',
        target: 'technicalRiskAssessmentHolding',
      },
    },
    {
      data: {
        id: 'externalVendor:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-thirdPartyRiskAssessment:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'externalVendor:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'thirdPartyRiskAssessment:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'externalVendor:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-vendorRiskAssessment:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'externalVendor:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'vendorRiskAssessment:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'productionEnvironmentProvisioning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-vulnerabilityRemediation:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'productionEnvironmentProvisioning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'vulnerabilityRemediation:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'disasterRecoveryPlanning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-websiteMonitoring:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'disasterRecoveryPlanning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'websiteMonitoring:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'productionEnvironmentProvisioning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-websiteMonitoring:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'productionEnvironmentProvisioning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'websiteMonitoring:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
  ],
  hideableEdges: [
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-accountManagement:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'accountManagement:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-amsServiceRequest:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'amsServiceRequest:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-applicationRiskAssessment:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'applicationRiskAssessment:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-architectureAssurance:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'architectureAssurance:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-cloudServiceOnboardingProcess',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'cloudServiceOnboardingProcess',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-dataClassification:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'dataClassification:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-developmentEnvironmentProvisioning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'developmentEnvironmentProvisioning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-disasterRecoveryPlanning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'disasterRecoveryPlanning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-dynamicApplicationSecurityTesting:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'dynamicApplicationSecurityTesting:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-encryptionAtRest:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'encryptionAtRest:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-encryptionInTransit:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'encryptionInTransit:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-externalSources:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'externalSources:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-externalVendor:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'externalVendor:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-externalWebsites:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'externalWebsites:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-fullArchitectureReview:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'fullArchitectureReview:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-initialSolutionCompliance:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'initialSolutionCompliance:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-multifactorAuthentication:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'multifactorAuthentication:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-performanceLoadTestingProcessCompletion:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'performanceLoadTestingProcessCompletion:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-performanceLoadTestingProcessEngagement:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'performanceLoadTestingProcessEngagement:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-privacyRiskAssessment:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'privacyRiskAssessment:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-productionEnvironmentProvisioning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'productionEnvironmentProvisioning:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-securityDesignReview:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'securityDesignReview:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-securityInformationEventManagement:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'securityInformationEventManagement:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-serviceDeskKnowledgeBase:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'serviceDeskKnowledgeBase:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-serviceTakeOn:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'serviceTakeOn:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-softwareCompositionAnalysis:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'softwareCompositionAnalysis:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-solutionDesign:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'solutionDesign:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-staticApplicationSecurityTesting:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'staticApplicationSecurityTesting:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-technicalRiskAssessment',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'technicalRiskAssessment',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-thirdPartyRiskAssessment:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'thirdPartyRiskAssessment:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-vendorRiskAssessment:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'vendorRiskAssessment:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-vulnerabilityRemediation:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'vulnerabilityRemediation:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
    {
      data: {
        id: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1-websiteMonitoring:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        source: 'voyagerSetup:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
        target: 'websiteMonitoring:0d0c154cb610f459bc12d1f79c7fab85ebbc5dd1',
      },
    },
  ],
  phaseNodes: [
    {
      data: {
        id: 'Plan & Design',
        color: '#fdffe8',
        totalTasks: 25,
        statusCounts: {
          Active: 0,
          Complete: 0,
          Bypassed: 0,
          Future: 25,
          Approved: 0,
          Rejected: 0,
        },
        completionPercent: 0,
        label: 'Plan & Design: 0%',
      },
    },
    {
      data: {
        id: 'Build, Test & Deploy',
        color: '#dbeaff',
        totalTasks: 14,
        statusCounts: {
          Active: 0,
          Complete: 0,
          Bypassed: 0,
          Future: 14,
          Approved: 0,
          Rejected: 0,
        },
        completionPercent: 0,
        label: 'Build, Test & Deploy: 0%',
      },
    },
    {
      data: {
        id: 'Governance',
        color: '#ffdfdf',
        totalTasks: 1,
        statusCounts: {
          Active: 0,
          Complete: 0,
          Bypassed: 0,
          Future: 1,
          Approved: 0,
          Rejected: 0,
        },
        completionPercent: 0,
        label: 'Governance: 0%',
      },
    },
    {
      data: {
        id: 'Initiation',
        color: '#e5ffe7',
        totalTasks: 4,
        statusCounts: {
          Active: 1,
          Complete: 1,
          Bypassed: 0,
          Future: 2,
          Approved: 0,
          Rejected: 0,
        },
        completionPercent: 25,
        label: 'Initiation: 25%',
      },
    },
  ],
};

export default elements;
